version: "3.8"

services:
  app:
    image: app
    container_name: app
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    user: dev
    volumes:
      - ..:/usr/src/app
    tty: true

  db:
    image: db
    container_name: db
    build:
      context: ..
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    tty: true
