version: "3.8"

services:
  api:
    image: api
    container_name: api
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile
    user: dev
    volumes:
      - ../..:/usr/src/app
    tty: true

  db:
    image: db
    container_name: db
    build:
      context: ..
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    tty: true
